# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbcd4269a730816b2b84e980208d2b76e08f3baaee12643a55128a0193370cb07c461ee9310b40bce96ad2490c4493e9c0326ff350ee8f0d3f84447e337e361

test:
  secret_key_base: 8be1e58b409cd6b595948497b5ae19610d6d20efbaefd92d4b922dab770e0a8fe43c9f79167e4a7cc963f895b12c9610ca61595f51f6b6654a6437aafbddcc2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
